#include "PatientFileLoader.h"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

#include "Patient.h"
#include "Vitals.h"

using namespace std;


// Splits a string on the supplied delimiter into a vector of substrings.
// Empty trailing fields are preserved so that callers can distinguish
// "missing" optional fields from genuinely empty ones.
static vector<string> split(const string& input, char delim)
{
    vector<string> tokens;
    string token;
    istringstream stream(input);
    while (std::getline(stream, token, delim)) {
        tokens.push_back(token);
    }
    return tokens;
}


std::vector<Patient*> PatientFileLoader::loadPatientFile(const std::string& file)
{
    vector<Patient*> patients{};

    std::ifstream inFile(file);
    if (!inFile.is_open()) {
        std::cerr << "PatientFileLoader: failed to open '" << file << "'" << std::endl;
        return patients;
    }

    string line;
    while (std::getline(inFile, line)) {
        if (line.empty()) {
            continue;
        }

        // Expected line format:
        //   uid|lastname,firstname|dd-mm-yyyy|disease|bt,bp,hr,rr;bt,bp,hr,rr;...
        // The uid is regenerated by the Patient class so the first field is ignored.
        const vector<string> fields = split(line, '|');
        if (fields.size() < 4) {
            std::cerr << "PatientFileLoader: skipping malformed line: " << line << std::endl;
            continue;
        }

        const string& nameField = fields[1];
        const auto comma = nameField.find(',');
        const string lastName = (comma == string::npos) ? nameField : nameField.substr(0, comma);
        const string firstName = (comma == string::npos) ? string{} : nameField.substr(comma + 1);

        std::tm birthday{};
        std::istringstream birthdayStream(fields[2]);
        birthdayStream >> std::get_time(&birthday, "%d-%m-%Y");

        Patient* p = new Patient(firstName, lastName, birthday);
        p->addDiagnosis(fields[3]);

        // Vitals are optional and may contain multiple semicolon-separated readings.
        if (fields.size() >= 5 && !fields[4].empty()) {
            for (const string& vitalEntry : split(fields[4], ';')) {
                if (vitalEntry.empty()) {
                    continue;
                }
                const vector<string> tokens = split(vitalEntry, ',');
                if (tokens.size() != 4) {
                    std::cerr << "PatientFileLoader: skipping malformed vitals: " << vitalEntry << std::endl;
                    continue;
                }
                try {
                    const float bt = std::stof(tokens[0]);
                    const int bp = std::stoi(tokens[1]);
                    const int hr = std::stoi(tokens[2]);
                    const int rr = std::stoi(tokens[3]);
                    Vitals* v = new Vitals(bt, bp, hr, rr);
                    p->addVitals(v);
                }
                catch (const std::exception& e) {
                    std::cerr << "PatientFileLoader: bad numeric vitals '" << vitalEntry
                              << "': " << e.what() << std::endl;
                }
            }
        }

        patients.push_back(p);
    }

    return patients;
}
